package frc.robot.constants;

import org.frcteam3539.BulldogLibrary.INIConfiguration.BBConstants;

public class IDConstants extends BBConstants {

    public IDConstants() {
        super("/home/lvuser/IDConstants.ini", true);
        save();
    }

    /* =================== DO NOT MODIFY BELOW =================== */
    public static int turretMotorID = 14;
    public static int shootMotorID = 12;
    public static int hoodMotorID = 11;
    public static int funnelDeployCanCoderID = 24;
    public static int funnelDeployMotorID = 9;
    public static int outerIntakeMotorID = 8;
    public static int innerIntakeMotorID = 10;
    public static int feedWheelMotorID = 13;
    public static int feedBeltMotorID = 15;
    public static int pigeonID = 26;
    public static int BRSteerID = 1;
    public static int FRDriveID = 2;
    public static int FRSteerID = 3;
    public static int BLDriveID = 4;
    public static int BLSteerID = 5;
    public static int FLDriveID = 6;
    public static int FLSteerID = 7;
    public static int BLCanCoderID = 20;
    public static int FLCanCoderID = 21;
    public static int BRCanCoderID = 22;
    public static int FRCanCoderID = 23;
    public static int FunnelDeployCanCoder = 24;
    /* =================== END OF AUTOGENERATED BLOCK ============ */

}
