package frc.robot.constants;

import org.frcteam3539.BulldogLibrary.INIConfiguration.BBConstants;

public class IntakeConstants extends BBConstants {

    public IntakeConstants() {
        super("/home/lvuser/IntakeConstants.ini", true);
        save();
    }

    /* =================== DO NOT MODIFY BELOW =================== */
    public static double funnelDeployOffset = 0.533;
    public static double funnelDeployDiscontPoint = 0.75;
    public static double funnelDeploySoftMax = 105.0;
    public static double funnelDeploySoftMin = -42.0;
    public static double funnelDeployMotorToMechanism = 64.44;
    public static double funnelDeploykP = 64.0;
    public static double funnelDeploykI = 0.0;
    public static double funnelDeploykD = 0.0;
    public static double funnelDeploykV = 6.16;
    public static double funnelDeploykG = 0.5;
    public static double funnelDeployAcceleration = 2.0;
    public static double funnelDeployCruiseVelocity = 0.8;
    public static double groundFunnelDeployAngle = -42.0;
    public static double outerIntakeVoltage = 0.0;
    public static double innerIntakeVoltage = 0.0;
    public static double homeFunnelDeployAngle = 100.0;
    public static double handOffFunnelDeployAngle = 80.0;
    public static double humanFunnelDeployAngle = 80.0;
    public static double outerIntakeDiameter = 0.0;
    public static double innerIntakeDiameter = 0.0;
    public static double feedWheelDiameter = 4.75;
    public static double feedBeltDiameter = 1.5;
    public static double outerIntakeSS = 100.0;
    public static double innerIntakeSS = 100.0;
    public static double feedWheelSS = 1000;
    public static double feedBeltSS = 800;
    public static double feedWheelkP = 0.1;
    public static double feedWheelkI = 0.0;
    public static double feedWheelkD = 0.0;
    public static double feedBeltkP = 0.1;
    public static double feedBeltkI = 0.0;
    public static double feedBeltkD = 0.0;
    /* =================== END OF AUTOGENERATED BLOCK ============ */

}
