package frc.robot.constants;

import org.frcteam3539.BulldogLibrary.INIConfiguration.BBConstants;

public class ShooterConstants extends BBConstants {

    public ShooterConstants() {
        super("/home/lvuser/ShooterConstants.ini", true);
        save();
    }

    /* =================== DO NOT MODIFY BELOW =================== */
    /** rot per sec^2 */
    public static double shootAcceleration = 500;
    public static double shootkD = 0.0;
    public static double shootkI = 0.0;
    public static double shootkP = 0.1;
    public static double shootkV = 0.0;
    /** rot per sec^2 */
    public static double hoodAcceleration = 0.0;
    /** rot per sec */
    public static double hoodCruiseVelocity = 0.0;
    public static double hoodkD = 0.0;
    public static double hoodkI = 0.0;
    public static double hoodkP = 0.0;
    public static double hoodkV = 0.0;
    /** rot per sec^2 */
    public static double turretRotateAcceleration = 400;
    /** rot per sec */
    public static double turretRotateCruiseVelocity = 120;
    public static double turretRotatekD = 0.0;
    public static double turretRotatekI = 0.0;
    public static double turretRotatekP = 5;
    public static double turretRotatekV = 0.0;
    /** in inches */
    public static double shootDiameter = 4.0;
    public static double shootSS = 1500;
    /* =================== END OF AUTOGENERATED BLOCK ============ */

}
